[project]
name = 'bitto-contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-deposit'

[[project.requirements]]
contract_id = 'SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token'

# [contracts.message-board-v2]
# path = 'contracts/message-board.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.fungible-token]
# path = 'contracts/fungible-token.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.message-board-with-clarity-v4]
# path = 'contracts/message-board-with-clarity-v4.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.lending-borrowing]
# path = 'contracts/lending-borrowing.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.tokenized-vault]
# path = 'contracts/tokenized-vault.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.semi-fungible-token]
# path = 'contracts/semi-fungible-token.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.non-fungible-token]
# path = 'contracts/non-fungible-token.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.nft-marketplace]
# path = 'contracts/nft-marketplace.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.non-fungible-token-royalty-std]
# path = 'contracts/non-fungible-token-royalty-std.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.semi-fungible-token-inspired-by-3525]
# path = 'contracts/semi-fungible-token-inspired-by-3525.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.trustless-agents-std]
# path = 'contracts/trustless-agents-std.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.identity-registry]
# path = 'contracts/identity-registry.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.flash-loan]
# path = 'contracts/flash-loan.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.rental-non-fungible-token]
# path = 'contracts/rental-non-fungible-token.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.royalty-bearing-non-fungible-token]
# path = 'contracts/royalty-bearing-non-fungible-token.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.swap-core]
# path = 'contracts/swap-core.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.hook-enabled-fungible-token]
# path = 'contracts/hook-enabled-fungible-token.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.notary]
# path = 'contracts/notary.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.minimal-soulbound-nft]
# path = 'contracts/minimal-soulbound-nft.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.meta-proxy]
# path = 'contracts/meta-proxy.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.consumable-nft]
# path = 'contracts/consumable-nft.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.account-abstraction]
# path = 'contracts/account-abstraction.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.diamonds]
# path = 'contracts/diamonds.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.non-fungible-token-with-physical-assets]
# path = 'contracts/non-fungible-token-with-physical-assets.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.rental-nft-with-user-extension]
# path = 'contracts/rental-nft-with-user-extension.clar'
# clarity_version = 4
# epoch = 'latest'

# [contracts.time-non-fungible-token]
# path = 'contracts/time-non-fungible-token.clar'
# clarity_version = 4
# epoch = 'latest'

[contracts.payable-token]
path = 'contracts/payable-token.clar'
clarity_version = 4
epoch = 'latest'

[contracts.native-meta-tx]
path = 'contracts/native-meta-tx.clar'
clarity_version = 4
epoch = 'latest'

[contracts.security-token]
path = 'contracts/security-token.clar'
clarity_version = 4
epoch = 'latest'

[contracts.consensual-soulbound-token]
path = 'contracts/consensual-soulbound-token.clar'
clarity_version = 4
epoch = 'latest'

[contracts.hyperlink-nft]
path = 'contracts/hyperlink-nft.clar'
clarity_version = 4
epoch = 'latest'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'