[project]
name = "business-use-cases"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"
requirements = []

# [contracts.decentralized-ai-models-network]
# path = "contracts/decentralized-ai-models-network.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.decentralized-ai-marketplace]
# path = "contracts/decentralized-ai-marketplace.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.llm-training-network]
# path = "contracts/llm-training-network.clar"
# clarity_version = 3
# epoch = "latest"

[contracts.robot-training-data-marketplace]
path = "contracts/robot-training-data-marketplace.clar"
clarity_version = 3
epoch = "latest"

[contracts.robot-realtime-data-marketplace]
path = "contracts/robot-realtime-data-marketplace.clar"
clarity_version = 3
epoch = "latest"

# [contracts.robot-communication-network]
# path = "contracts/robot-communication-network.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.robot-payment-network]
# path = "contracts/robot-payment-network.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.medical-data-exchange-for-enterprise]
# path = "contracts/medical-data-exchange-for-enterprise.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.clinical-trial-data-marketplace]
# path = "contracts/clinical-trial-data-marketplace.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.epidemiological-data-marketplace]
# path = "contracts/epidemiological-data-marketplace.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.decentralized-clinical-trial-network]
# path = "contracts/decentralized-clinical-trial-network.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.decentralized-scientific-research]
# path = "contracts/decentralized-scientific-research.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.ip-property-registry]
# path = "contracts/ip-property-registry.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.decentralized-salesforce]
# path = "contracts/decentralized-salesforce.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.micropayment-with-revenue-sharing]
# path = "contracts/micropayment-with-revenue-sharing.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.ip-registry]
# path = "contracts/ip-registry.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.insurance-for-ip-breach]
# path = "contracts/insurance-for-ip-breach.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.decentralized-cdn-network]
# path = "contracts/decentralized-cdn-network.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.decentralized-gpu-network]
# path = "contracts/decentralized-gpu-network.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.decentralized-advertisement-network]
# path = "contracts/decentralized-advertisement-network.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.legal-counsel-network]
# path = "contracts/legal-counsel-network.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.prediction-market]
# path = "contracts/prediction-market.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.perp-dex-for-prediction-market]
# path = "contracts/perp-dex-for-prediction-market.clar"
# clarity_version = 3
# epoch = "latest"

[contracts.tokenized-equity-platform]
path = "contracts/tokenized-equity-platform.clar"
clarity_version = 3
epoch = "latest"

[contracts.undercollateralized-lending]
path = "contracts/undercollateralized-lending.clar"
clarity_version = 3
epoch = "latest"

# [contracts.onchain-fx-market]
# path = "contracts/onchain-fx-market.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.onchain-kyc]
# path = "contracts/onchain-kyc.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.onchain-etf-market]
# path = "contracts/onchain-etf-market.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.gpu-backed-private-credit]
# path = "contracts/gpu-backed-private-credit.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.infrastructure-debt]
# path = "contracts/infrastructure-debt.clar"
# clarity_version = 4
# epoch = "latest"

# [contracts.senior-direct-lending]
# path = "contracts/senior-direct-lending.clar"
# clarity_version = 4
# epoch = "latest"

# [contracts.mezzanine-junior-debt]
# path = "contracts/mezzanine-junior-debt.clar"
# clarity_version = 4
# epoch = "latest"

# [contracts.distressed-debt]
# path = "contracts/distressed-debt.clar"
# clarity_version = 4
# epoch = "latest"

# [contracts.asset-based-lending]
# path = "contracts/asset-based-lending.clar"
# clarity_version = 4
# epoch = "latest"

# [contracts.real-estate-finance]
# path = "contracts/real-estate-finance.clar"
# clarity_version = 4
# epoch = "latest"

# [contracts.venture-debt]
# path = "contracts/venture-debt.clar"
# clarity_version = 4
# epoch = "latest"

# [contracts.specialty-finance]
# path = "contracts/specialty-finance.clar"
# clarity_version = 4
# epoch = "latest"

# [contracts.cash-flow-modeling]
# path = "contracts/cash-flow-modeling.clar"
# clarity_version = 4
# epoch = "latest"

# [contracts.dcf-valuation-modeling]
# path = "contracts/dcf-valuation-modeling.clar"
# clarity_version = 4
# epoch = "latest"

# [contracts.leveraged-buyout-modeling]
# path = "contracts/leveraged-buyout-modeling.clar"
# clarity_version = 4
# epoch = "latest"

# [contracts.virtual-power-plants]
# path = "contracts/virtual-power-plants.clar"
# clarity_version = 4
# epoch = "latest"

# [contracts.microgrids]
# path = "contracts/microgrids.clar"
# clarity_version = 4
# epoch = "latest"

# [contracts.small-modular-nuclear-reactors]
# path = "contracts/small-modular-nuclear-reactors.clar"
# clarity_version = 4
# epoch = "latest"

# [contracts.incentives-to-deploy-new-solar-panels]
# path = "contracts/incentives-to-deploy-new-solar-panels.clar"
# clarity_version = 4
# epoch = "latest"

# [contracts.carbon-credit-tokenization]
# path = "contracts/carbon-credit-tokenization.clar"
# clarity_version = 4
# epoch = "latest"

# [contracts.decentralized-cellular-network]
# path = "contracts/decentralized-cellular-network.clar"
# clarity_version = 4
# epoch = "latest"

# [contracts.decentralized-telecom-network]
# path = "contracts/decentralized-telecom-network.clar"
# clarity_version = 4
# epoch = "latest"

# [contracts.long-range-wireless-network]
# path = "contracts/long-range-wireless-network.clar"
# clarity_version = 4
# epoch = "latest"

# [contracts.fixed-wireless-access-network]
# path = "contracts/fixed-wireless-access-network.clar"
# clarity_version = 4
# epoch = "latest"

# [contracts.decentralizing-food-delivery]
# path = "contracts/decentralizing-food-delivery.clar"
# clarity_version = 4
# epoch = "latest"

# [contracts.decentralized-ridesharing]
# path = "contracts/decentralized-ridesharing.clar"
# clarity_version = 4
# epoch = "latest"

# [contracts.decentralized-geolocation-network]
# path = "contracts/decentralized-geolocation-network.clar"
# clarity_version = 4
# epoch = "latest"

# [contracts.decentralized-satellite-network]
# path = "contracts/decentralized-satellite-network.clar"
# clarity_version = 4
# epoch = "latest"

# [contracts.cashflow-statement]
# path = "contracts/cashflow-statement.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.balance-sheet]
# path = "contracts/balance-sheet.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.income-statement]
# path = "contracts/income-statement.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.statement-of-shareholders-equity]
# path = "contracts/statement-of-shareholders-equity.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.sms-one-time-password]
# path = "contracts/sms-one-time-password.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.dtcc]
# path = "contracts/dtcc.clar"
# clarity_version = 3
# epoch = "latest"

[contracts.tokenized-stocks-platform]
path = "contracts/tokenized-stocks-platform.clar"
clarity_version = 4
epoch = "latest"

# [contracts.airline-seat-ticketing-service]
# path = "contracts/airline-seat-ticketing-service.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.pro-baseball-ticketing]
# path = "contracts/pro-baseball-ticketing.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.pro-football-ticketing]
# path = "contracts/pro-football-ticketing.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.pro-basketball-ticketing]
# path = "contracts/pro-basketball-ticketing.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.semiconductor-manufacturing]
# path = "contracts/semiconductor-manufacturing.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.semiconductor-design-process]
# path = "contracts/semiconductor-design-process.clar"
# clarity_version = 3
# epoch = "latest"

[contracts.wafer-fabrication-process]
path = "contracts/wafer-fabrication-process.clar"
clarity_version = 4
epoch = "latest"

# [contracts.chip-atp-process]
# path = "contracts/chip-atp-process.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.battery-electric-bus-production]
# path = "contracts/battery-electric-bus-production.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.lithium-battery-monitoring]
# path = "contracts/lithium-battery-monitoring.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.humanoid-robot-production]
# path = "contracts/humanoid-robot-production.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.robotics-oem]
# path = "contracts/robotics-oem.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.robotics-data-sharing]
# path = "contracts/robotics-data-sharing.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.robot-deployment-planing-system]
# path = "contracts/robot-deployment-planing-system.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.robot-supply-chain-network]
# path = "contracts/robot-supply-chain-network.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.robot-maintainance-automation]
# path = "contracts/robot-maintainance-automation.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.home-battery-storage]
# path = "contracts/home-battery-storage.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.aircraft-assembly-process]
# path = "contracts/aircraft-assembly-process.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.tokenized-artwork-exchange]
# path = "contracts/tokenized-artwork-exchange.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.sports-player-ip-mgmt]
# path = "contracts/sports-player-ip-mgmt.clar"
# clarity_version = 3
# epoch = "latest"

[contracts.tokenized-sports-club]
path = "contracts/tokenized-sports-club.clar"
clarity_version = 3
epoch = "latest"

# [contracts.onchain-kyb]
# path = "contracts/onchain-kyb.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.onchain-kyt]
# path = "contracts/onchain-kyt.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.onchain-obs]
# path = "contracts/onchain-obs.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.onchain-kya]
# path = "contracts/onchain-kya.clar"
# clarity_version = 3
# epoch = "latest"



















[contracts.kgst-stablecoin]
path = "contracts/kgst-stablecoin.clar"
clarity_version = 4
epoch = "latest"

# [contracts.gold-backed-stablecoin]
# path = "contracts/gold-backed-stablecoin.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.cbdc]
# path = "contracts/cbdc.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.tokenized-deposit]
# path = "contracts/tokenized-deposit.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.outcome-linked-public-spending]
# path = "contracts/outcome-linked-public-spending.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.transferable-innovation-across-cities]
# path = "contracts/transferable-innovation-across-cities.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.cross-organizational-service-orchestration]
# path = "contracts/cross-organizational-service-orchestration.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.outcome-based-bond]
# path = "contracts/outcome-based-bond.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.milestone-based-funding]
# path = "contracts/milestone-based-funding.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.programmable-policy-making]
# path = "contracts/programmable-policy-making.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.fractional-investment-fund]
# path = "contracts/fractional-investment-fund.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.cross-agency-coordination]
# path = "contracts/cross-agency-coordination.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.smart-city]
# path = "contracts/smart-city.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.cross-sector-coordination]
# path = "contracts/cross-sector-coordination.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.real-time-service-delivery]
# path = "contracts/real-time-service-delivery.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.multi-actor-funding]
# path = "contracts/multi-actor-funding.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.data-sharing]
# path = "contracts/data-sharing.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.automated-policy-making]
# path = "contracts/automated-policy-making.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.dynamic-zoning]
# path = "contracts/dynamic-zoning.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.municiple-program-execution]
# path = "contracts/municiple-program-execution.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.municiple-bond]
# path = "contracts/municiple-bond.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.outcome-based-vendor-payment]
# path = "contracts/outcome-based-vendor-payment.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.programmable-climate-policy]
# path = "contracts/programmable-climate-policy.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.agentic-state]
# path = "contracts/agentic-state.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.NFT-for-local-art-funding]
# path = "contracts/NFT-for-local-art-funding.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.city-token]
# path = "contracts/city-token.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.tokenized-city-land-nft]
# path = "contracts/tokenized-city-land-nft.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.government-procurement]
# path = "contracts/government-procurement.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.car-title-registry]
# path = "contracts/car-title-registry.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.performance-zoning]
# path = "contracts/performance-zoning.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.incentive-zoning]
# path = "contracts/incentive-zoning.clar"
# clarity_version = 3
# epoch = "latest"

# [contracts.form-based-codes]
# path = "contracts/form-based-codes.clar"
# clarity_version = 3
# epoch = "latest"

[contracts.automated-leadership-team-in-company]
path = "contracts/automated-leadership-team-in-company.clar"
clarity_version = 4
epoch = "latest"

[contracts.auto-directors-board-members]
path = "contracts/automated-directors-and-board-members-in-company.clar"
clarity_version = 4
epoch = "latest"

[contracts.auto-ceo]
path = "contracts/automated-chief-executive-officer-in-company.clar"
clarity_version = 4
epoch = "latest"

[contracts.auto-cto]
path = "contracts/automated-chief-technical-officer-in-company.clar"
clarity_version = 4
epoch = "latest"

[contracts.auto-cmo]
path = "contracts/automated-chief-marketing-officer-in-company.clar"
clarity_version = 4
epoch = "latest"

[contracts.auto-coo]
path = "contracts/automated-chief-operating-officer-in-company.clar"
clarity_version = 4
epoch = "latest"

[contracts.secure-drop-whistleblower]
path = "contracts/secure-drop-style-whistleblowing-platform.clar"
clarity_version = 4
epoch = "latest"

[contracts.globa-leaks-whistleblower]
path = "contracts/globa-leaks-style-whistleblowing-platform.clar"
clarity_version = 4
epoch = "latest"

[contracts.wiki-leaks-whistleblower]
path = "contracts/wiki-leaks-style-whistleblowing-platform.clar"
clarity_version = 4
epoch = "latest"

[contracts.gap-style-whistleblowing-platform]
path = "contracts/gap-style-whistleblowing-platform.clar"
clarity_version = 4
epoch = "latest"

[contracts.alacs-style-whistleblowing-platform]
path = "contracts/alacs-style-whistleblowing-platform.clar"
clarity_version = 4
epoch = "latest"

[contracts.navex-global-whistleblower]
path = "contracts/navex-global-style-whistleblowing-platform.clar"
clarity_version = 4
epoch = "latest"

[contracts.convercent-whistleblower]
path = "contracts/convercent-style-whistleblowing-platform.clar"
clarity_version = 4
epoch = "latest"

[contracts.sec-whistleblower]
path = "contracts/sec-whistleblower-program-style-whistleblowing-platform.clar"
clarity_version = 4
epoch = "latest"

[contracts.cftc-whistleblower]
path = "contracts/cftc-whistleblower-program-style-whistleblowing-platform.clar"
clarity_version = 4
epoch = "latest"

[contracts.osha-whistleblower]
path = "contracts/osha-whistleblower-protection-program-style-whistleblowing-platform.clar"
clarity_version = 4
epoch = "latest"

[contracts.flnra-tips-whistleblower]
path = "contracts/flnra-tips-style-whistleblowing-platform.clar"
clarity_version = 4
epoch = "latest"

[contracts.fca-style-whistleblowing-platform]
path = "contracts/fca-style-whistleblowing-platform.clar"
clarity_version = 4
epoch = "latest"

[contracts.hhs-oig-whistleblower]
path = "contracts/hhs-oig-hotline-style-whistleblowing-platform.clar"
clarity_version = 4
epoch = "latest"

[contracts.nhs-speak-up-whistleblower]
path = "contracts/nhs-speak-up-guardians-style-whistleblowing-platform.clar"
clarity_version = 4
epoch = "latest"

[contracts.keybase-style-whistleblowing-platform]
path = "contracts/keybase-style-whistleblowing-platform.clar"
clarity_version = 4
epoch = "latest"

[contracts.tor-onion-style-whistleblowing-platform]
path = "contracts/tor-onion-style-whistleblowing-platform.clar"
clarity_version = 4
epoch = "latest"

[contracts.allvoices-style-whistleblowing-platform]
path = "contracts/allvoices-style-whistleblowing-platform.clar"
clarity_version = 4
epoch = "latest"

[contracts.faceup-style-whistleblowing-platform]
path = "contracts/faceup-style-whistleblowing-platform.clar"
clarity_version = 4
epoch = "latest"

[contracts.automated-asset-management-firm]
path = "contracts/automated-asset-management-firm.clar"
clarity_version = 4
epoch = "latest"

[contracts.esim-activation-manager]
path = "contracts/esim-activation-manager.clar"
clarity_version = 4
epoch = "latest"

[contracts.white-labeled-stablecoin-issurance]
path = "contracts/white-labeled-stablecoin-issurance.clar"
clarity_version = 4
epoch = "latest"

[contracts.buy-now-pay-later]
path = "contracts/buy-now-pay-later.clar"
clarity_version = 4
epoch = "latest"

[contracts.token-curation-platform]
path = "contracts/token-curation-platform.clar"
clarity_version = 4
epoch = "latest"

[contracts.token-launchpad]
path = "contracts/token-launchpad.clar"
clarity_version = 4
epoch = "latest"
