[project]
name = "business-use-cases"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"
requirements = []

[contracts.infrastructure-debt]
path = "contracts/infrastructure-debt.clar"
clarity_version = 4
epoch = "latest"
